import { FluentProviderProps } from '@fluentui/react-components';
import {
  useButtonStyles,
  useMenuButtonStyles,
  useSplitButtonStyles,
  useToggleButtonStyles,
  type ButtonState,
  type MenuButtonState,
  type SplitButtonState,
  type ToggleButtonState,
} from './components/react-button';

export { getIntrinsicElementProps, slot } from '@fluentui/react-utilities';
export {
  motionTokens,
  makeStyles,
  mergeClasses,
} from '@fluentui/react-components';

export type {
  ButtonAppearance,
  ButtonProps,
  ButtonSlots,
  ButtonState,
  MenuButtonProps,
  MenuButtonSlots,
  MenuButtonState,
  SplitButtonProps,
  SplitButtonSlots,
  SplitButtonState,
  ToggleButtonProps,
  ToggleButtonState,
} from './components/react-button';
export {
  Button,
  MenuButton,
  SplitButton,
  ToggleButton,
  buttonClassNames,
  menuButtonClassNames,
  renderButton,
  renderMenuButton,
  renderSplitButton,
  renderToggleButton,
  splitButtonClassNames,
  toggleButtonClassNames,
  useButton,
  useButtonStyles,
  useMenuButton,
  useMenuButtonStyles,
  useSplitButton,
  useSplitButtonStyles,
  useToggleButton,
  useToggleButtonStyles,
} from './components/react-button';
export type {
  BorderRadiusTokens,
  BrandVariants,
  Brands,
  ColorPaletteAnchor,
  ColorPaletteBeige,
  ColorPaletteBerry,
  ColorPaletteBlue,
  ColorPaletteBrass,
  ColorPaletteBrown,
  ColorPaletteCornflower,
  ColorPaletteCranberry,
  ColorPaletteDarkGreen,
  ColorPaletteDarkOrange,
  ColorPaletteDarkRed,
  ColorPaletteForest,
  ColorPaletteGold,
  ColorPaletteGrape,
  ColorPaletteGreen,
  ColorPaletteLavender,
  ColorPaletteLightGreen,
  ColorPaletteLightTeal,
  ColorPaletteLilac,
  ColorPaletteMagenta,
  ColorPaletteMarigold,
  ColorPaletteMink,
  ColorPaletteNavy,
  ColorPalettePeach,
  ColorPalettePink,
  ColorPalettePlatinum,
  ColorPalettePlum,
  ColorPalettePumpkin,
  ColorPalettePurple,
  ColorPaletteRed,
  ColorPaletteRoyalBlue,
  ColorPaletteSeafoam,
  ColorPaletteSteel,
  ColorPaletteTeal,
  ColorPaletteTokens,
  ColorPaletteYellow,
  ColorTokens,
  CurveTokens,
  CustomizableTypographyStyle,
  CustomizableTypographyStyles,
  DurationTokens,
  Font,
  FontFamilyCustomFontTokens,
  FontFamilyTokens,
  FontSizeTokens,
  FontStyleTokens,
  FontVariants,
  FontWeightCustomFontTokens,
  FontWeightTokens,
  Greys,
  HorizontalSpacingTokens,
  LineHeightTokens,
  PartialTheme,
  ShadowBrandTokens,
  ShadowTokens,
  SpacingTokens,
  StrokeWidthTokens,
  Theme,
  TokenName,
  TypographyStyle,
  TypographyStyles,
  VerticalSpacingTokens,
  ZIndexTokens,
} from './components/tokens';
export {
  applyFonts,
  black,
  createDarkTheme,
  createLightTheme,
  darkTheme,
  extractNeutralTokens,
  grey,
  lightTheme,
  themeToTokensObject,
  tokens,
  typographyStyles,
  white,
} from './components/tokens';

export const CAP_STYLE_HOOKS: NonNullable<
  FluentProviderProps['customStyleHooks_unstable']
> = {
  useButtonStyles_unstable: (state) => {
    return useButtonStyles(state as ButtonState);
  },
  useMenuButtonStyles_unstable: (state) => {
    return useMenuButtonStyles(state as MenuButtonState);
  },
  useSplitButtonStyles_unstable: (state) => {
    return useSplitButtonStyles(state as SplitButtonState);
  },
  useToggleButtonStyles_unstable: (state) => {
    return useToggleButtonStyles(state as ToggleButtonState);
  },
};
